In [40]:
# confirm in our virtual environment
import sys
print(sys.executable)

/Users/hussaintaheri/Desktop/sports-win-predictor/venv/bin/python

In [41]:
import os 
print(os.getcwd())

/Users/hussaintaheri/Desktop/sports-win-predictor/notebooks

In [42]:
import pandas as pd
df = pd.read_csv("../data/nba_pbp_2020_2025.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0,0,22401186,2,PT12M00.00S,1,0,NaN,0,NaN,...,0.0,0.0,0,NaN,Start of 1st Period (1:12 PM EST),period,start,0,0,1
1,1,1,22401186,4,PT12M00.00S,1,1610612737,ATL,1631230,Barlow,...,NaN,NaN,0,h,Jump Ball Barlow vs. Carter Jr.: Tip to Mann,Jump Ball,NaN,1,0,2
2,2,2,22401186,7,PT11M43.00S,1,1610612737,ATL,1629611,Mann,...,NaN,NaN,0,h,MISS Mann 4' Fadeaway Jumper,Missed Shot,Fadeaway Jump Shot,1,2,3
3,3,3,22401186,8,PT11M40.00S,1,1610612753,ORL,1628976,Carter Jr.,...,NaN,NaN,0,v,Carter Jr. REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,4
4,4,4,22401186,9,PT11M23.00S,1,1610612753,ORL,203484,Caldwell-Pope,...,NaN,NaN,0,v,MISS Caldwell-Pope 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,5

In [43]:
# view columns to drop which ones we want be using for our model
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'gameId', 'actionNumber', 'clock',
       'period', 'teamId', 'teamTricode', 'personId', 'playerName',
       'playerNameI', 'xLegacy', 'yLegacy', 'shotDistance', 'shotResult',
       'isFieldGoal', 'scoreHome', 'scoreAway', 'pointsTotal', 'location',
       'description', 'actionType', 'subType', 'videoAvailable', 'shotValue',
       'actionId'],
      dtype='object')

In [44]:
df = df.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0', 'actionNumber', 'teamTricode', 'personId', 'playerName',
       'playerNameI', 'xLegacy', 'yLegacy', 'shotDistance', 'shotResult',
       'isFieldGoal', 'description', 'subType', 'videoAvailable', 'shotValue',
       'actionId', 'pointsTotal', 'teamId'], index = 1)

In [45]:
df.isna().count()

gameId        3282178
clock         3282178
period        3282178
scoreHome     3282178
scoreAway     3282178
location      3282178
actionType    3282178
dtype: int64

In [46]:
df.head(20)

      gameId        clock  period  scoreHome  scoreAway location   actionType
0   22401186  PT12M00.00S       1        0.0        0.0      NaN       period
2   22401186  PT11M43.00S       1        NaN        NaN        h  Missed Shot
3   22401186  PT11M40.00S       1        NaN        NaN        v      Rebound
4   22401186  PT11M23.00S       1        NaN        NaN        v  Missed Shot
5   22401186  PT11M19.00S       1        NaN        NaN        h      Rebound
6   22401186  PT11M15.00S       1        2.0        0.0        h    Made Shot
7   22401186  PT10M58.00S       1        NaN        NaN        v  Missed Shot
8   22401186  PT10M55.00S       1        NaN        NaN        v      Rebound
9   22401186  PT10M49.00S       1        2.0        3.0        v    Made Shot
10  22401186  PT10M35.00S       1        NaN        NaN        h     Turnover
11  22401186  PT10M35.00S       1        NaN        NaN        v          NaN
12  22401186  PT10M31.00S       1        2.0        5.0        v    Made Shot
13  22401186  PT10M13.00S       1        NaN        NaN        h  Missed Shot
14  22401186  PT10M11.00S       1        NaN        NaN        v      Rebound
15  22401186  PT10M06.00S       1        NaN        NaN        v  Missed Shot
16  22401186  PT10M01.00S       1        NaN        NaN        v      Rebound
17  22401186  PT09M51.00S       1        NaN        NaN        v  Missed Shot
18  22401186  PT09M49.00S       1        NaN        NaN        v      Rebound
19  22401186  PT09M49.00S       1        NaN        NaN        h         Foul
20  22401186  PT09M49.00S       1        2.0        6.0        v   Free Throw

In [39]:
# fill missing values for home and away so it carries the values forward and not update whenever a score changes
# use forward fill method
df[["scoreHome"]["scoreAway"]] = df.groupby(["gameId"])[["scoreHome", "scoreAway"]].ffill()

KeyError: 'gameId'

In [38]:
df.head(20)

    scoreHome  scoreAway
0         0.0        0.0
2         0.0        0.0
3         0.0        0.0
4         0.0        0.0
5         0.0        0.0
6         2.0        0.0
7         2.0        0.0
8         2.0        0.0
9         2.0        3.0
10        2.0        3.0
11        2.0        3.0
12        2.0        5.0
13        2.0        5.0
14        2.0        5.0
15        2.0        5.0
16        2.0        5.0
17        2.0        5.0
18        2.0        5.0
19        2.0        5.0
20        2.0        6.0